### ISSUE TITLE
any plans to add album art support?

### ISSUE THREAD

**Issue by irockdude554** [riverrrrrr/DiscordSoundCloud#1]
i noticed while listening to some songs the discord rich presence icon would be the soundcloud logo, do you have any plans on adding support of changing that to album art covers?

**Comment by KurozeroPB** [comment]
It's pretty much impossible to do such with how discord's rich presence works.
Right now you'd have to manually add assets one by one with I think 140 assets max.
There is however an issue open on the discord-rpc repo which suggests allowing to upload temporary assets, but I don't know if this is actually planned by discord to implement.

**Comment by riverrrrrr** [comment]
Yeah @kurozeropb is right. My initial plans were to add that but then quickly learned the limitations rich presence had.
