### ISSUE TITLE
Switching from "Playing" to "Listening to"

### ISSUE THREAD

**Issue by Collussus** [riverrrrrr/DiscordSoundCloud#3]
As the title suggests, are you able to change the app now to make it say "Listening to Soundcloud" instead of "Playing", like it does for Spotify?

**Comment by ChristoferMinestar** [comment]
Yeah, was about to post this

**Comment by riverrrrrr** [comment]
Hey guys! This is currently not possible with discord-rpc but I will add it to the list of planned features if and when they decide to let developers change the status!
